60 feat carousel
Thenlie/Streamability pull request #455
Opened 2023-08-14 15:56 UTC by maxh1231

- Created `ShowCarousel` that accepts a `data` and `count` prop. `data` will be sliced into `count` chunks to display `count` number of `ShowCards` per carousel step. This is how we'll conditionally render different-sized carousels depending on screen widths. Closes #60 

    ## Carousel Screenshot
    ![image](https://github.com/Thenlie/Streamability/assets/41771785/8bf4d826-a551-4a78-9502-b9b660d88f66)

- Created `ShowCarouselPlacholder` to be rendered while `ShowCarousel` is loading. Closes #75 

   ## Placeholder Screenshot
   ![image](https://github.com/Thenlie/Streamability/assets/41771785/18b828fb-08c2-4e35-9ddb-6e91d351e8a1)

- `ShowCarousel` now being rendered on landing page to display trending movies and tv shows. Additionally, modified TV and Movie requests to return a `showType` property with the expected values of `'tv'` or `'movie'`. This enables more dynamic behavior when rendering `ShowCards`. Closes #93 

- `ShowCarousel` now being rendered on user's dashboard to display the user's watch queue. Modified Supabase `profile` table to accept type `text` to create a custom string ID which includes `tv-{id}` and `movie-{id}` flags. This allows us to determine whether to request TV or Movie details with a given ID. Closes #101

- `ShowCarousel` now being rendered on `ShowDetailsScreen` to display recommendations. Closes #102

2023-08-14 16:39 UTC, Thenlie commented on src/components/ShowCarouselPlaceholder.tsx
For this placeholder, would it make more sense to leverage the `ShowCardPlaceholder` component directly? This would ensure if that one is updated, this automatically gets the same changes.

2023-08-14 16:41 UTC, Thenlie commented on src/screens/FeaturedSearchScreen.tsx
> +    }, []);
Out of scope for this PR, but we can likely make this a custom hook `useTrendingShows()` or something.

2023-08-14 16:42 UTC, Thenlie commented on src/screens/FeaturedSearchScreen.tsx
> +                    size={5}
I see we are hardcoding the size of these carousels currently. Do we have a plan to dynamically update these on screen size change? I think we should create a ticket for this with 'TODO' comments as I imagine this currently is non-functional on mobile. Let me know if I am mistaken.

2023-08-14 16:44 UTC, Thenlie commented on src/screens/DashboardScreen.tsx
> +                >
Out of scope of this PR but I think we might want to make some custom button wrappers. All of these buttons could just be `<ContainedButton />`

2023-08-15 01:09 UTC, Thenlie commented on src/screens/DashboardScreen.tsx
> +                >
Created #456

2023-08-15 01:13 UTC, Thenlie commented on src/screens/FeaturedSearchScreen.tsx
> +    }, []);
Created #457

2023-08-15 03:28 UTC, maxh1231 commented on src/components/ShowCarouselPlaceholder.tsx
Created #458

2023-08-15 03:35 UTC, Thenlie commented on src/screens/FeaturedSearchScreen.tsx
> +                    size={5}
Created https://github.com/Thenlie/Streamability/issues/458

2023-08-15 04:20 UTC, Thenlie requested changes
<img width="1039" alt="image" src="https://github.com/Thenlie/Streamability/assets/41388783/61577265-1a6d-4d5c-8012-1138273ed341">

Carousel storybook doesn't appear to be working on my end. In browser it works okay but will need some horizontal padding to keep the buttons of the edge off the screen.

2023-08-15 04:22 UTC, Thenlie commented on src/components/CarouselChildren.tsx
I think this component could exist in the ShowCarousel component file. It shouldn't really be needed anywhere else and both files are pretty small.

2023-08-15 04:24 UTC, Thenlie commented on src/components/ShowCarousel.tsx
> +                <Carousel>{handleDataSlice(data)}</Carousel>
Did you check out `wrapAround` prop? It looked kind of nice to me.

2023-08-16 04:57 UTC, Thenlie commented
Made some updates to the component.

## Screenshots

![image](https://github.com/Thenlie/Streamability/assets/41388783/f35c74ea-4e2e-4d83-858c-9d5b91c85bce)
![image](https://github.com/Thenlie/Streamability/assets/41388783/fd1722d8-fc24-4291-9ec5-9398cc59d8db)

2023-08-16 04:59 UTC, Thenlie approved these changes

2023-08-16 05:14 UTC, merged